stages:
  - containerize
  - deploy

variables:
  DOCKER_IMAGE: moreillon/authentication-manager
  KUBERNETES_DEPLOYMENT: authentication-manager-deployment

containerization:
  stage: containerize
  script:
    - docker build -t ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - pwd
  #  - kubectl apply -f deployment.yml
  #  - kubectl rollout restart deployment/${KUBERNETES_DEPLOYMENT}
  environment:
    name: production
