stages:
  - containerization
  - deploy

variables:
  APPLICATION_NAME: authentication
  CONTAINER_REGISTRY: moreillon
  DOCKER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CERTIFICATE_DOMAIN: api.authentication.maximemoreillon.com

containerization:
  stage: containerization
  script:
    # Docker hub login
    - echo ${DOCKER_HUB_USERNAME}
    - echo ${DOCKER_HUB_PASSWORD}
    - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
    # Build and push Docker image
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
