stages:
  - containerization
  - deploy

variables:
  APPLICATION_NAME: authentication
  DOCKER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CERTIFICATE_DOMAIN: api.authentication.maximemoreillon.com

containerization:
  stage: containerization
  script:
    - cp ${ENV} ./.env
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
