stages:
  - containerization
  - deploy

variables:
  DOCKER_IMAGE: moreillon/authentication-manager
  KUBERNETES_DEPLOYMENT: authentication-manager-deployment


containerization:
  stage: containerization
  script:
    - echo ${SECRETS} > secrets.js
    - cat secrets.js
  #  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  #  - docker build -t ${DOCKER_IMAGE} .
  #  - docker push ${DOCKER_IMAGE}
  #  - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - pwd
  #  - kubectl apply -f deployment.yml
  #  - kubectl rollout restart deployment/${KUBERNETES_DEPLOYMENT}
  environment:
    name: production
