stages:
  - containerization
  - deploy

variables:
  APPLICATION_NAME: authentication
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  DOCKER_IMAGE_TAGGED: ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  CERTIFICATE_DOMAIN: api.authentication.maximemoreillon.com

containerization:
  stage: containerization
  only:
    - master
  tags:
    - moreillon
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Build and push Docker image
    - docker build -t ${DOCKER_IMAGE} .
    - docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_TAGGED}
    - docker push ${DOCKER_IMAGE}
    - docker push ${DOCKER_IMAGE_TAGGED}
    # Cleanup
    - docker image rm ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE_TAGGED}

deployment:
  stage: deploy
  tags:
    - moreillon
  only:
    - master
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
