apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-microservice-deployment
  template:
    metadata:
      labels:
        app: authentication-microservice-deployment
    spec:
      containers:
      - name: authentication-microservice
        image: moreillon/authentication-microservice
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: authentication-microservice-service
  name: authentication-microservice-service
spec:
  ports:
  - port: 8088
    nodePort: 30111
  selector:
    app: authentication-microservice-deployment
  type: LoadBalancer
