apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-microservice
  template:
    metadata:
      labels:
        app: authentication-microservice
    spec:
      containers:
      - name: authentication-microservice
        image: 192.168.1.2:5000/authentication-microservice
        ports:
        - containerPort: 7088
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: authentication-microservice
  name: authentication-microservice
spec:
  selector:
    app: authentication-microservice
  type: NodePort
  ports:
  - port: 7088
    targetPort: 7088
    nodePort: 30111
