apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: 192.168.1.2:5000/authentication
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  ports:
  - port: 80
    nodePort: 30111
  selector:
    app: authentication
  type: NodePort
