apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  selector:
    matchLabels:
      run: authentication
  replicas: 1
  template:
    metadata:
      labels:
        run: authentication
    spec:
      containers:
      - name: authentication
        image: 192.168.1.2:5000/authentication-microservice
        ports:
        - containerPort: 7088
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    run: authentication
spec:
  ports:
  - port: 7088
    protocol: TCP
  selector:
    run: authentication
