apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-manager-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-manager-deployment
  template:
    metadata:
      labels:
        app: authentication-manager-deployment
    spec:
      containers:
      - name: authentication-manager
        image: moreillon/authentication-manager
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: authentication-manager-service
  name: authentication-manager-service
spec:
  ports:
  - port: 8088
    nodePort: 30111
  selector:
    app: authentication-manager-deployment
  type: LoadBalancer
